apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-dev-role
  namespace: app-dev
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
